# Generated by Django 4.0.5 on 2023-03-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
