# Generated by Django 4.0.5 on 2023-03-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_f_nac_usuarios_fnac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipousu', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fnac',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fregistro',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
