# Generated by Django 4.0.5 on 2023-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='correo',
            new_name='genero',
        ),
    ]
